# /home/siisi/portfolio/docker-compose.prod.yml

services:
  db:
    image: postgres:latest
    restart: always
    env_file: 
      - .env.prod
    environment:
      - ENVIRONMENT=prod
    volumes:
      - portfolio_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=prod
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=prod
    depends_on:
      db:
        condition: service_healthy
    command: >
      gunicorn portfolio.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 60
    ports:
      - "8085:8000"
    volumes:
      - ./media:/app/media
      - ./static:/app/static

volumes:
  portfolio_data_prod: {}
