# Generated by Django 5.2.1 on 2025-05-31 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Used for modal_id, e.g. 'portfolioModal1'", unique=True)),
                ('thumbnail', models.CharField(help_text="Static path: 'assets/img/portfolio/...jpg'", max_length=200)),
                ('image', models.CharField(help_text='Static path for modal image', max_length=200)),
                ('description', models.TextField(help_text='Short blurb under the title')),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='List of bullet-point features', size=None)),
            ],
        ),
    ]
