# Generated by Django 5.2.1 on 2025-05-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='Full external URL for the ‘See Project’ button', max_length=300),
        ),
    ]
