# Generated by Django 5.2.1 on 2025-06-06 10:01
# portfolio_app/migrations/0004_migrate_features_and_add_translations.py

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_contactmessage_alter_project_url'),
    ]

    operations = [
        # 1) Convert the old varchar[] → jsonb (so Postgres does to_json)
        migrations.RunSQL(
            sql=(
                "ALTER TABLE portfolio_app_project "
                "ALTER COLUMN features TYPE jsonb "
                "USING to_json(features);"
            ),
            reverse_sql=(
                "ALTER TABLE portfolio_app_project "
                "ALTER COLUMN features TYPE varchar[] "
                "USING features::varchar[];"
            ),
        ),

        # 2) Alter the model field itself so Django knows it's now JSONField
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text="Mapping of language codes to feature lists",
            ),
        ),

        # 3) Now add your title_<lang> and description_<lang> columns
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_pt',
            field=models.CharField(max_length=100, null=True),
        ),

        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(help_text='Short blurb under the title', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(help_text='Short blurb under the title', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(help_text='Short blurb under the title', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_pt',
            field=models.TextField(help_text='Short blurb under the title', null=True),
        ),

        # 4) And for ContactMessage if you need those too
        migrations.AddField(
            model_name='contactmessage',
            name='subject_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_es',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_pt',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_pt',
            field=models.TextField(null=True),
        ),
    ]
